##############################################
# Config applying to the application
##############################################
application:
  name: Data Returns - Pollution Inventory
  version: 1.0.0
##############################################
# Config applying to the HAPI web server
##############################################
server:
  sampleInterval: 60000     # log load every minute
  timeout: 60000            # Time out requests after one minute and return a 503 error - Service Unavailable
  cache:                    # The redis cache storing authorized user details
    authorization:
      timeToLive: 145440000 # Time to live in milliseconds (1 day)
  authorization:
    cookie:                 # The cookie associated with the authorization cache
      timeToLive:
      ironCookiePassword: 'vghu87VkhjgvTG796kjhbOHsqa&^(*&gsVJ'
##############################################
# API options
##############################################
api:
  requestTimeout: 20000

##############################################
# Logging options
##############################################
logging:
  file: 'logs/datareturns.log'

##############################################
# Miscellaneous options
##############################################
css:
  compressed: true          # minify css