application:
  name: Data Returns - Pollution Inventory

server:
  cache:
    authorization:
      timeToLive: 145440000 # The session cookie and the session cache ttl in milliseconds

  authorization:
    cookie:
      timeToLive:
      ironCookiePassword: 'vghu87VkhjgvTG796kjhbOHsqa&^(*&gsVJ'
