application:
  name: Data Returns - Pollution Inventory

server:
  cache:
    authorization:
      timeToLive: 145440000 # The session cache time to live in milliseconds

  authorization:
    cookie:
      timeToLive:
      ironCookiePassword: 'vghu87VkhjgvTG796kjhbOHsqa&^(*&gsVJ'

  timeout: 60000 # Time out requests after one minute and return a 503 error - Service Unavailable

